export const BASE_URL = process.env.NEXT_PUBLIC_WEBFLOW_URL;
export const WORKSPACE_TOKEN = process.env.NEXT_PUBLIC_WEBFLOW_WORKSPACE_TOKEN;
export const COLLECTION_ID = process.env.NEXT_PUBLIC_WEBFLOW_COLLECTION_ID;
export const DAM_COLLECTION_ID = process.env.NEXT_PUBLIC_DAM_COLLECTION_ID;
export const JUDGES_COLLECTION_ID =
  process.env.NEXT_PUBLIC_JUDGES_COLLECTION_ID;
export const TEAMS_COLLECTION_ID = process.env.NEXT_PUBLIC_TEAMS_COLLECTION_ID;
export const SPONSOR_LOGO_COLLECTION_ID =
  process.env.NEXT_PUBLIC_SPONSOR_LOGO_COLLECTION_ID;
export const PATREON_COLLECTION_ID =
  process.env.NEXT_PUBLIC_PATREON_COLLECTION_ID;
